system:
  project: PROJE
  exp_name: Lifespan_MAE
  n_threads: 8
  ckpt_dir: '/opt/localdata/data/usr-envs/ruiying/Code/foundation/MoE_foundation_v3/checkpoint/MAE_checkpoints'
  seed: 0

train:
  type: 'mae'
  lr: 2e-4
  batch_size: 4
  epochs: 300
  niter: 200
  mask_ratio: 0.75
  optimizer: 'AdamW'
  weight_decay: 0.05
  betas: [0.9, 0.95]

data:
  normalize: true
  norm_perc: 99.5
  remove_bg: true
  aug: true
  aug_prob: 0.35
  patch_size: [96, 96, 96]
  mae_root: '/labs/wanglab/projects/lifespan-T1T2FA'
  mae_domain_file: '/opt/localdata/data/usr-envs/ruiying/Code/foundation/MoE_foundation_v3/cfg/mae_domains.txt'
  mae_val_domain_file: '/opt/localdata/data/usr-envs/ruiying/Code/foundation/MoE_foundation_v3/cfg/mae_val_domains.txt'
  mae_test_list: '/opt/localdata/data/usr-envs/ruiying/Code/foundation/MoE_foundation_v3/cfg/test_sub_list.csv'
model:
  modalities: ['T1w', 'T2w', 'FA', 'MD']
  age_groups: ['fetal', 'neonatal', 'infant', 'child', 'adult', 'elderly']
  moe_type: 'hierarchical'
  embed_dim: 512
  load_pretrain: true
  pretrain_model: "/opt/localdata/data/usr-envs/ruiying/Code/foundation/MoE_foundation_v3/MAE_checkpoint/second/best_mae.pth"
